### ISSUE TITLE
Income tax Additional rate threshold is defined differently from other thresholds

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/openfisca-uk#122]
In https://github.com/PSLmodels/openfisca-uk/blob/master/openfisca_uk/parameters/tax/income_tax/rates/uk.yaml, the Basic Rate and Higher rate thresholds are defined relative to the Personal Allowance (thresholds of 0 and 37500, respectively), but the Additional rate is defined as 150000, which is the actual threshold per https://www.gov.uk/income-tax-rates. Is this because the Personal Allowance has phased out by then? Is there a way to define the thresholds such that they match this table? Could be clearer.

Band | Taxable income | Tax rate
-- | -- | --
Personal Allowance | Up to £12,570 | 0%
Basic rate | £12,571 to £50,270 | 20%
Higher rate | £50,271 to £150,000 | 40%
Additional rate | over £150,000 | 45%

**Comment by nikhilwoodruff** [comment]
The rates in ```uk.yaml``` are aligned with the rates on the [next page](https://www.gov.uk/income-tax-rates/previous-tax-years) of that link, which are the thresholds on income above the personal allowance. Personally I think that's clearer, since in this table you have both the personal allowance and the actual threshold changing together.

**Comment by nikhilwoodruff** [comment]
But to be clear, this shouldn't have any effect on revenue, since we're making a deduction of £0 from the person earning £150k, as opposed to not making a £0 deduction.

**Comment by MaxGhenis** [comment]
Sounds good, thanks @nikhilwoodruff!
