### ISSUE TITLE
Option for Simulation to point to DataFrames in memory

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/openfisca-uk#44]
Currently, the `openfisca_uk.tools.simulation.Simulation` constructor loads data from CSV files. It would be speedier if there were an option to call [`load_frs()`](https://github.com/PSLmodels/openfisca-uk/blob/master/openfisca_uk/tools/simulation.py#L82) to load the FRS data once, then point to the three DataFrames. Doesn't matter much when running it once, but could help for optimizations with hundreds or thousands of simulations.

Alternatively, if there were a function to replace the reform parameters in an existing `Simulation`, that could do the trick.

**Comment by nikhilwoodruff** [comment]
I think both of these are possible: seems like we should:

- allow the Simulation constructor to accept three DataFrames, or an object encapsulating them, instead of loading them manually
- add a reform() method to the Simulation class, that returns a copy of the Simulation with a passed reform applied to the tax-benefit system

**Comment by nikhilwoodruff** [comment]
This was actually fixed in #53 - ```PopulationSim``` has an optional argument ```frs_data``` which is a tuple of ```person_df, benunit_df, household_df```. The second option of calculating variables under a reform, using existing populations, seems like it is a [lot more complex](https://github.com/openfisca/openfisca-core/issues/848).
